#!/bin/bash

h_string=$'Welcome to Hivestats, a tool to help you navigate UC Berkeley EECS instructional computers. \nBuilt by James Rigassio, with inspiration taken from Allen Guo\'s Hivemind (http://aguo.us/hivemind/) \nAvailable commands / flags are:\n
login: remotely connects you to the least busy server via SSH (prompts for credentials)\n
show: displays a table of usage data for all EECS instructional servers\n
-v: gives version info\n
-h: displays this menu'
if [ -z "$1" ] || [ "$1" == "-h" ]; then
  echo "$h_string"
else
  case "$1" in
    -v)
    echo "v1.0. Collaborate on this project! Github URL -> https://github.com/jrigassio/hivestats";;
    show)
    data=$(wget -qO- https://labs.aguo.us/hivemind/data/latest.json)
    
    login)
    echo "optimal login" ;;
    *)
    echo "Invalid argument: ${1}"
  esac
fi
